repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      types: ['file']
      files: \.(py|pyx|pxd)$
      additional_dependencies: [flake8-bugbear]
