name: hummingbot-minimal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - pip>=21.1.2
  - coverage>=5.5
  - nose>=1.3.7
  - nose-exclude
  - flake8>=3.7.9
  - setuptools>=50.3.2
  - pre-commit>=2.18.1
  - aiohttp==3.7.4.post0
  - aiokafka>=0.7.1
  - asyncssh>=2.7.2
  - aiounittest>=1.4.1
  - bidict
  - cryptography>=2.8
  - numpy>=1.20.1
  - numpy-base>=1.20.1
  - pandas>=1.2.1
  - prompt_toolkit=3.0.20
  - protobuf>=4.21.0
  - psutil>=5.7.2
  - ptpython>=3.0.20
  - pyperclip==1.7.0
  - pydantic=1.9
  - requests>=2.22.0
  - scipy>=1.6.2
  - six=1.14.0
  - sqlalchemy>=1.4,<1.4.99
  - tabulate>=0.8.9
  - ujson>=1.35
  - websockets>=9.1
  - zlib>=1.2.11
  - pip:
    - aioprocessing==2.0.0
    - aioresponses==0.7.2
    - cachetools==4.0.0
    - commlib-py==0.10.6
    - cython==3.0a7
    - docker>=5.0.3
    - dydx-v3-python==1.0.10
    - ethsnarks-loopring==0.1.5
    - injective-py>=0.5.9.3
    - pandas_ta==0.3.14b
    - python-telegram-bot==12.4.2
    - ruamel-yaml==0.16.10
    - git+https://github.com/CoinAlpha/python-signalr-client.git
